# Generated by Django 4.2.7 on 2023-12-05 05:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_cliente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
